### ISSUE TITLE
Question about where did you use latent_gan?

### ISSUE THREAD

**Issue by xiaomingjie** [optas/latent_3d_points#10]
HI @optas 
Thanks for sharing your code.
I ran the code as the guide said. It seems that you did use AE but I couldn't find where did you put latent_gan in the AE. I couldn't even find "import gan or latent_gan" in training files.
Hope for your reply.

**Comment by optas** [comment]
Hi, I updated the GAN based code and added two detailed notebooks for raw/latent GAN training with vanilla and W-GAN-GP objectives. You will need to pull;)
