### ISSUE TITLE
'approx_match' is not defined?

### ISSUE THREAD

**Issue by VikVelev** [optas/latent_3d_points#12]
Hello,
First of all, great paper and great results. I have a few questions regarding the architecture and compiling.
I managed to compile everything, using python2.7 and all the tested versions of the libraries (except CUDA, but the compilation was successful (i think?)so I ignored it), but as soon as I run the notebook I get stomped by this message: 

```python
NameError: global name 'approx_match' is not defined
```

My second question is how does 1D Convolution with Stride 1 and Kernel 1 actually work in your case with point clouds? Isn't that just multiplication?

**Comment by VikVelev** [comment]
Fixed the first issue by installing CUDA 8.0, but my question about the 1D convolutions still stands :) thanks for your time.

**Comment by optas** [comment]
Hi,

I am glad you figured out the CUDA stuff.

1D convolution happens wrt. to each point. That is indeed a multiplication (dot-product) between the three coordinates (x,y,z) of each point and the learned kernel.

Best,
