### ISSUE TITLE
No module named latend_3d_points.src.ae_templates

### ISSUE THREAD

**Issue by howard84527** [optas/latent_3d_points#13]
Hi,
I have exported PYTHONPATH but I still got an error below:

ImportErrorTraceback (most recent call last)
<ipython-input-8-6ff735e636f5> in <module>()
      1 import os.path as osp
      2 
----> 3 from latent_3d_points.src.ae_templates import mlp_architecture_ala_iclr_18, default_train_params
      4 from latent_3d_points.src.autoencoder import Configuration as Conf
      5 from latent_3d_points.src.point_net_ae import PointNetAutoEncoder

ImportError: No module named latent_3d_points.src.ae_templates

Thank you.

**Comment by optas** [comment]
I am assuming you are trying to run a notebook. Right?

Can you load _ANY_ function under latent_3d_points.src.xx.py {xx can be any module)? If not, then you have not added it the code to the PYTHONPATH.

To add it, notice that you should give the (top) folder where your latent_3d_points.xxx reside.

Best,

**Comment by howard84527** [comment]
Right, I can't run the function under latent_3d_points.src.xxx.py .
I use export PYTHONPATH=/..../.../latent_3d_points. Is it correct?

Thank you.

**Comment by optas** [comment]
Please try this,

export PYTHONPATH=${PYTHONPATH}:xx/yy/zz

where zz contains the cloned repo. 

See also here:
https://askubuntu.com/questions/470982/how-to-add-a-python-module-to-syspath

**Comment by airportdc** [comment]
> Right, I can't run the function under latent_3d_points.src.xxx.py .
> I use export PYTHONPATH=/..../.../latent_3d_points. Is it correct?
> 
> Thank you.

This is because the code in notebook is 
`from latent_3d_points.src.ae_templates import mlp_architecture_ala_iclr_18, default_train_params` , 
when you append your path into `PYTHONPATH`, you should use `'/path/to/latent_3d_points/..'` instead. 
Hope this would help.
