### ISSUE TITLE
The original shapenetcore dataset

### ISSUE THREAD

**Issue by zeal-up** [optas/latent_3d_points#17]
Hi, thanks for sharing your work! Can you tell me where to download the original shapenetcore(57k 3D shapes) . In shapenet website, the shapenetcore dataset only contains ~51k 3d shapes.
![image](https://user-images.githubusercontent.com/40826585/49016811-3500e280-f1c2-11e8-98e0-aed54f4d295c.png)

**Comment by linhaojia13** [comment]
I encounter the same problem. Did you fix it?

**Comment by CRISZJ** [comment]
I alose have the same problem,did you fix it?

**Comment by ammar-ahmed999** [comment]
The shapenet.org is not available. it would be very helpful if you could provide an alternate to obtain the dataset.
