### ISSUE TITLE
unknown symbol error

### ISSUE THREAD

**Issue by Vahe1994** [optas/latent_3d_points#3]
Hi!
Thank you for your work , it was very good. But I have an issue with running structural losses. 
I changed make file with my paths for cuda ,nvcc and tf. Compilation was  successful , but when I tried to run import in jupyter notebook there is pop up  an error: "undefined symbol: _ZTIN10tensorflow8OpKernelE". After searching in internet, many people have that issue too,but there is not solution for this problem that work for everyone.I tried everything,but  nothing worked for me. Maybe you encountered with this problem and can give some advice how to fix it.

I tried to run this project on two different computer, with various  environments:
1) Gpu Nvidia K80 Cuda 8.0 cudnn 7.5 anaconda python 2.7 tensorflow 1.3.0
2) Gpu Nvidia K80 Cuda 8.0 cudnn 7.5 anaconda  python 2.7 tensorflow 1.4.1
3)Gpu Nvidia K80 Cuda 8.0 cudnn 7.5  anaconda  python 3.6 tensorflow 1.4.1
compiling with  g++5 a and g++ 4
4)GPU Nvidia 1050Ti cudnn 7.5  anaconda  python 2.7 tensorflow 1.3.0
5)GPU Nvidia 1050Ti cudnn 7.5 anaconda  python 3.6 tensorflow 1.3.0

Maybe problem is that I have cudnn 7.5 instead 6.0? 

With best regards, 
Egiazarian V.G.

**Comment by optas** [comment]
Egiazarian,

Thank very much you for your interest. I have not encountered this problem myself and I cannot really help. Nevertheless, your assumption on the version of cudnn can indeed be the issue. Please write back if you have found a solution. 
Best regards,

**Comment by Ardibid** [comment]
I faced the same issue, the problem was with the version of Tensorflow. Make sure that you are using Tensorflow 1.3.

**Comment by Vahe1994** [comment]
As I mention before I tried 1.3 tensorflow, but I installed it from conda and it was mistake.
It turned out that  something wrong with conda's version of tensorflow. After uninstalling it, and installing from pip(tensorflow version 1.3.0), everything start to work very well. 

Thank you all for your response!!!

With best regards,
Egiazarian V.G.
