### ISSUE TITLE
How to draw point cloud like this paper?

### ISSUE THREAD

**Issue by GitBoSun** [optas/latent_3d_points#4]
I'm interested in how to draw point cloud in 3D vision with shadow. I tried myself with OpenGL but failed. I'm appreciate if anyone can help me. Thanks!

**Comment by optas** [comment]
We used Mitsuba: https://www.mitsuba-renderer.org

**Comment by saedrna** [comment]
Is this done by first create a sphere geometry in mitsuba for every point? Or manually create sphere to a obj using point clouds?

Han

**Comment by olkido** [comment]
Hi Han,
We created one sphere per point in front of a white background. We used scripts (MATLAB) to export Mitsuba .xml 's. 
Olga
