### ISSUE TITLE
how to import module?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [optas/latent_3d_points#6]
![screenshot from 2018-04-15 19-47-39](https://user-images.githubusercontent.com/29811853/38784839-f6403fce-40e5-11e8-856a-f8c1f2945ae0.png)
how can I solve this problem?

**Comment by Vahe1994** [comment]
Try to remove dot's before latent_3d_points. 
P.S. Same issue you can find here https://stackoverflow.com/questions/41816973/modulenotfounderror-what-does-it-mean-main-is-not-a-package. Maybe it will help.
